language: ruby
rvm:
  - 1.9.3
  - 1.9.2
script: bundle exec rake install; bundle exec rake generate
notifications:
  irc: "irc.freenode.org#parttimelegend"
  email:
    on_success: never
    on_failure: never
