language: ruby
rvm:
  - 1.9.3
script: bundle exec rake generate
notifications:
  irc: "rowling.freenode.net#parttimelegend"
  email:
    on_success: never
    on_failure: never
branches:
  only:
    - master
 
